eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

server:
  port: 8889
spring:
  application:
    name: eureka-service
  cloud:
    config:
      uri: http://localhost:8888
      #uri: http://config-service:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
