server:
  port: 9181
spring:
  datasource:
    url: jdbc:mysql://heartbeat-mysql:3306/heartbeat?createDatabaseIfNotExist=true
    username: heartbeat
    password: heartbeat
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-server

logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8889/eureka/
  instance:
    hostname: localhost
