server:
  port: 8891
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
